version: '3.4'

services:
  wp:
    build:
      context: ./docker
#    Odkomentować po wprowadzeniu harbora
#    build:
#      context: .
#      target: local
    ports:
      - ${IP}:80:80 # change ip if required
    volumes:
      - ./docker/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
#      - ./docker/wp-config.php:/var/www/html/wp-config.php:rw coś namiąchane tu jest i nie mozna podmotowac pliku z configiem.
      - ./wp-app:/var/www/html # Full wordpress project
      - ./bluepayment:/var/www/html/wp-content/plugins/bluepayment
      - ./docker/build/wp-content/languages:/var/www/html/wp-content/languages/
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment: #do ustalenia co to za dziwny config. Część rzeczy na sztywno część z ENV.
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - mysql
    links:
      - mysql

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:8080:80
    links:
      - mysql:mysql

  mysql:
    image: mysql:5.7 # https://hub.docker.com/_/mysql/
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

volumes:
  db_data:
