#!/bin/bash

#chmod +x skrypt

cd ../../

zip -r bluepayment.zip bluepayment -x '*.gitignore*' '*BUILD.md*'  '*bluemedia-sdk-php/composer.json*' '*bluemedia-sdk-php/composer.lock*' '*bluemedia-sdk-php/.gitignore*'

printf "\n\n\nPaczka została spakowana do pliku bluepayment.zip w katalogu głównym projektu\n" 

printf "\n\nWersja wtyczki z kodu to: "
grep -i "@version" bluepayment/bluepayment.php | tr -d " " | cut -c 11-

printf "\nSprawdź na gitlabie, czy wersja zgadza się z tagiem.\n"

printf "\nPrzeglądarka otworzy się automatycznie.\n\n"

sleep 3;

x-www-browser https://gitlab.bsbox.pl/ecommerce/woocommerce/bluepayment/-/tags



